version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3335:3335"
    environment:
      - NODE_ENV=production
      - PORT=3335
      - MONGODB_URI=mongodb://mongo:27017/b2b-agent
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3335/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=b2b-agent
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

  redis:
    image: redis:7-alpine
    ports:
      - "0:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

volumes:
  mongo_data: 